server:
  port: ${APPLICATION_PORT:8092}
spring:
  application:
    name: hotelView
  config:
    import: optional:file:./util/.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:h2:mem:hotelView
    driver-class-name: org.h2.Driver
    username: ${DATABASE_USERNAME:username}
    password: ${DATABASE_PASSWORD:password}
  h2:
    console:
      enabled: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true